[package]
name = "segtri"
version = "0.1.2"
edition = "2024"
license = "MIT"
description = "Segment tree with customizable data type and update operations"
repository = "https://github.com/skr2005/segtri"
keywords = ["segment", "tree", "segtree"]
categories = ["data-structures"]
documentation = "https://docs.rs/segtri"

[dependencies]

[dev-dependencies]
serial_test = "3.2"